"""
mcts_geb — Monte Carlo Tree Search over the repo's e-graph rewrite rules.

"GEB" here follows the naming from the original prototype notebook
(Godel-Escher-Bach-flavored "equivalence exploration"): instead of running
plain equality saturation (apply every rule until fixpoint), we treat each
available rewrite *ruleset* as one action in a search tree, and use MCTS
(UCB1 selection, random rollout, backprop) to find a short, high-value
sequence of rule applications that minimizes extraction cost.

This package plugs into two existing rule sources in this repo:

1. Static rules — the algebraic / strength-reduction / commutativity /
   associativity identities defined in `egraph_bridge/egg_egraph.py`
   (the same rules created_algebraic_rules() etc. use for plain
   equality saturation elsewhere in the repo).

2. Learned rules — rules generated by the LLM pipeline in
   `learned_rules/` (llm_rule_generator -> rule_parser -> rule_filter),
   converted to egglog rewrites via `learned_rules/rule_to_egglog.py`.
   If no LLM provider is configured in `.env`, this pipeline
   automatically falls back to a deterministic stub response (see
   `learned_rules/llm_rule_generator.py:_get_stub_response`), so
   everything here runs out of the box with no API key.

Modules:
    rulesets.py      - builds the flat list of egglog Rulesets (actions)
    search.py         - the MCTS implementation (generalized from the
                         original notebook prototype)
    test_cases.py     - a sample set of expressions to optimize
    run_experiment.py - CLI entry point: builds rules, runs MCTS vs.
                         plain saturation on every test case, prints
                         and saves a results table
"""
